services:
  web:
    build: ./web
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    networks:
      - mynet

networks:
  mynet:
    driver: bridge